/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaceNameRouteImport } from './routes/place.$name'
import { Route as DestinationSlugRouteImport } from './routes/destination.$slug'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaceNameRoute = PlaceNameRouteImport.update({
  id: '/place/$name',
  path: '/place/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationSlugRoute = DestinationSlugRouteImport.update({
  id: '/destination/$slug',
  path: '/destination/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/planner': typeof PlannerRoute
  '/search': typeof SearchRoute
  '/destination/$slug': typeof DestinationSlugRoute
  '/place/$name': typeof PlaceNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/planner': typeof PlannerRoute
  '/search': typeof SearchRoute
  '/destination/$slug': typeof DestinationSlugRoute
  '/place/$name': typeof PlaceNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/planner': typeof PlannerRoute
  '/search': typeof SearchRoute
  '/destination/$slug': typeof DestinationSlugRoute
  '/place/$name': typeof PlaceNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/favorites'
    | '/planner'
    | '/search'
    | '/destination/$slug'
    | '/place/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/favorites'
    | '/planner'
    | '/search'
    | '/destination/$slug'
    | '/place/$name'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/favorites'
    | '/planner'
    | '/search'
    | '/destination/$slug'
    | '/place/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FavoritesRoute: typeof FavoritesRoute
  PlannerRoute: typeof PlannerRoute
  SearchRoute: typeof SearchRoute
  DestinationSlugRoute: typeof DestinationSlugRoute
  PlaceNameRoute: typeof PlaceNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place/$name': {
      id: '/place/$name'
      path: '/place/$name'
      fullPath: '/place/$name'
      preLoaderRoute: typeof PlaceNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination/$slug': {
      id: '/destination/$slug'
      path: '/destination/$slug'
      fullPath: '/destination/$slug'
      preLoaderRoute: typeof DestinationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FavoritesRoute: FavoritesRoute,
  PlannerRoute: PlannerRoute,
  SearchRoute: SearchRoute,
  DestinationSlugRoute: DestinationSlugRoute,
  PlaceNameRoute: PlaceNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
