// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

export function isSupabaseConfigured(): boolean {
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;
  
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) return false;
  if (
    SUPABASE_URL === "https://your-project.supabase.co" ||
    SUPABASE_PUBLISHABLE_KEY === "your-anon-key"
  ) {
    return false;
  }
  return true;
}

function createMockSupabaseClient() {
  const getStorageItem = (key: string) => {
    if (typeof window === "undefined") return null;
    return localStorage.getItem(key);
  };
  const setStorageItem = (key: string, val: string) => {
    if (typeof window === "undefined") return;
    localStorage.setItem(key, val);
  };

  // Auth Session Helper
  const getMockSession = () => {
    const raw = getStorageItem("supabase.auth.mock-session");
    if (!raw) return null;
    try {
      return JSON.parse(raw);
    } catch {
      return null;
    }
  };

  const setMockSession = (session: any) => {
    if (session) {
      setStorageItem("supabase.auth.mock-session", JSON.stringify(session));
    } else {
      if (typeof window !== "undefined") {
        localStorage.removeItem("supabase.auth.mock-session");
      }
    }
    // Notify auth state change listeners
    listeners.forEach((cb) => cb(session ? "SIGNED_IN" : "SIGNED_OUT", session));
  };

  const getMockUsers = () => {
    const raw = getStorageItem("supabase.auth.mock-users");
    if (!raw) {
      // Seed with demo account
      const seed = [
        {
          email: "demo.traveler@heritageverse.com",
          password: "DemoPassword123!",
          id: "demo-user-id",
          displayName: "Demo Traveler",
        },
      ];
      setStorageItem("supabase.auth.mock-users", JSON.stringify(seed));
      return seed;
    }
    try {
      return JSON.parse(raw);
    } catch {
      return [];
    }
  };

  const saveMockUser = (user: any) => {
    const users = getMockUsers();
    users.push(user);
    setStorageItem("supabase.auth.mock-users", JSON.stringify(users));
  };

  const listeners: Array<(event: string, session: any) => void> = [];

  const auth = {
    onAuthStateChange(callback: (event: string, session: any) => void) {
      listeners.push(callback);
      const session = getMockSession();
      // Invoke immediately in a timeout to match real Supabase async timing
      setTimeout(() => {
        callback(session ? "INITIAL_SESSION" : "SIGNED_OUT", session);
      }, 0);
      return {
        data: {
          subscription: {
            unsubscribe() {
              const idx = listeners.indexOf(callback);
              if (idx !== -1) listeners.splice(idx, 1);
            },
          },
        },
      };
    },
    async getSession() {
      const session = getMockSession();
      return { data: { session }, error: null };
    },
    async signUp({ email, password, options }: any) {
      const users = getMockUsers();
      if (users.some((u: any) => u.email.toLowerCase() === email.toLowerCase())) {
        return { data: { user: null, session: null }, error: new Error("User already exists") };
      }
      const userId = "user-" + Math.random().toString(36).substring(2, 11);
      const displayName = options?.data?.display_name || email.split("@")[0];
      const newUser = { email, password, id: userId, displayName };
      saveMockUser(newUser);

      const user = { id: userId, email, user_metadata: { display_name: displayName } };
      const session = { access_token: "mock-token-" + userId, user };
      setMockSession(session);
      return { data: { user, session }, error: null };
    },
    async signInWithPassword({ email, password }: any) {
      const users = getMockUsers();
      const matched = users.find(
        (u: any) => u.email.toLowerCase() === email.toLowerCase() && u.password === password
      );
      if (!matched) {
        // Autocreate demo traveler if demo email is requested and not found
        if (email.toLowerCase() === "demo.traveler@heritageverse.com") {
          const userId = "demo-user-id";
          const user = { id: userId, email, user_metadata: { display_name: "Demo Traveler" } };
          const session = { access_token: "mock-token-" + userId, user };
          setMockSession(session);
          return { data: { user, session }, error: null };
        }
        return { data: { user: null, session: null }, error: new Error("Invalid login credentials") };
      }
      const user = {
        id: matched.id,
        email: matched.email,
        user_metadata: { display_name: matched.displayName },
      };
      const session = { access_token: "mock-token-" + matched.id, user };
      setMockSession(session);
      return { data: { user, session }, error: null };
    },
    async signInWithOAuth({ provider }: any) {
      // Direct login to Demo Traveler or mock Google Traveler
      const userId = "google-user-id";
      const user = {
        id: userId,
        email: "google.traveler@heritageverse.com",
        user_metadata: { display_name: "Google Traveler" },
      };
      const session = { access_token: "mock-token-" + userId, user };
      setMockSession(session);
      return { data: { provider, url: window.location.origin }, error: null };
    },
    async signOut() {
      setMockSession(null);
      return { error: null };
    },
  };

  // Mock Database Query Builder
  class MockQueryBuilder {
    private tableName: string;
    private filters: Array<{ field: string; value: any }> = [];
    private orderByField: string | null = null;
    private orderAscending = true;
    private action: "select" | "insert" | "delete" | "update" = "select";
    private insertData: any = null;
    private updateData: any = null;
    private isSingle = false;

    constructor(tableName: string) {
      this.tableName = tableName;
    }

    select(columns?: string) {
      if (this.action !== "insert" && this.action !== "update") {
        this.action = "select";
      }
      return this;
    }

    insert(values: any) {
      this.action = "insert";
      this.insertData = values;
      return this;
    }

    update(values: any) {
      this.action = "update";
      this.updateData = values;
      return this;
    }

    delete() {
      this.action = "delete";
      return this;
    }

    eq(field: string, value: any) {
      this.filters.push({ field, value });
      return this;
    }

    order(column: string, options?: { ascending: boolean }) {
      this.orderByField = column;
      this.orderAscending = options?.ascending ?? true;
      return this;
    }

    maybeSingle() {
      this.isSingle = true;
      return this;
    }

    single() {
      this.isSingle = true;
      return this;
    }

    // Makes this class Thenable for `await` compatibility
    async then(onfulfilled?: (value: any) => any) {
      try {
        const res = await this.execute();
        if (onfulfilled) return onfulfilled(res);
        return res;
      } catch (err) {
        if (onfulfilled) return onfulfilled({ data: null, error: err });
        return { data: null, error: err };
      }
    }

    private async execute() {
      const storageKey = `mock-db-${this.tableName}`;
      let data: any[] = [];
      const raw = getStorageItem(storageKey);
      if (raw) {
        try {
          data = JSON.parse(raw);
        } catch {
          data = [];
        }
      }

      const currentSession = getMockSession();
      const currentUserId = currentSession?.user?.id ?? "anonymous";

      if (this.action === "select") {
        let filtered = [...data];
        for (const f of this.filters) {
          filtered = filtered.filter((row) => row[f.field] === f.value);
        }
        if (this.orderByField) {
          filtered.sort((a, b) => {
            const valA = a[this.orderByField!];
            const valB = b[this.orderByField!];
            if (valA == null || valB == null) return 0;
            if (valA < valB) return this.orderAscending ? -1 : 1;
            if (valA > valB) return this.orderAscending ? 1 : -1;
            return 0;
          });
        }
        if (this.isSingle) {
          return { data: filtered[0] || null, error: null };
        }
        return { data: filtered, error: null };
      }

      if (this.action === "insert") {
        const rowsToInsert = Array.isArray(this.insertData) ? this.insertData : [this.insertData];
        const newRows = rowsToInsert.map((row) => {
          const id = "row-" + Math.random().toString(36).substring(2, 11);
          return {
            id,
            created_at: new Date().toISOString(),
            user_id: currentUserId,
            ...row,
          };
        });
        data.push(...newRows);
        setStorageItem(storageKey, JSON.stringify(data));
        return { data: this.isSingle ? newRows[0] : newRows, error: null };
      }

      if (this.action === "update") {
        let updatedCount = 0;
        const updated = data.map((row) => {
          const matches = this.filters.every((f) => row[f.field] === f.value);
          if (matches) {
            updatedCount++;
            return {
              ...row,
              ...this.updateData,
              updated_at: new Date().toISOString(),
            };
          }
          return row;
        });
        if (updatedCount > 0) {
          setStorageItem(storageKey, JSON.stringify(updated));
        }
        const filtered = updated.filter((row) =>
          this.filters.every((f) => row[f.field] === f.value)
        );
        return { data: this.isSingle ? filtered[0] || null : filtered, error: null };
      }

      if (this.action === "delete") {
        let remaining = [...data];
        if (this.filters.length > 0) {
          remaining = remaining.filter((row) => {
            return !this.filters.every((f) => row[f.field] === f.value);
          });
        } else {
          remaining = [];
        }
        setStorageItem(storageKey, JSON.stringify(remaining));
        return { error: null };
      }

      return { data: null, error: new Error("Unsupported action") };
    }
  }

  const from = (tableName: string) => {
    return new MockQueryBuilder(tableName);
  };

  return { auth, from };
}

function createSupabaseClient() {
  if (!isSupabaseConfigured()) {
    console.warn(
      "[Supabase] Environment variables missing or placeholder detected. Falling back to local Mock Supabase Client."
    );
    return createMockSupabaseClient() as any;
  }

  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Add them in your deployment settings.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
